name: kerent_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.19.0
  intl_phone_field: ^3.1.0
  carousel_slider: ^4.0.0
  flutter_image_slideshow: ^0.1.2
  flutter_native_splash: ^2.2.8+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true                     
  ios: true                        
  image_path: "lib/assets/logo_kerent.png"  
  min_sdk_android: 21           
  adaptive_icon_background: "#000000" 
  adaptive_icon_foreground: "lib/assets/logo_kerent.png"
  web:
    generate: true
    image_path: "lib/assets/logo_kerent.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "lib/assets/logo_kerent.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "lib/assets/logo_kerent.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/devicon_google.png
    - lib/assets/icon_light_smartphone.png
    - lib/assets/search-icon.png
    - lib/assets/Laptop Silver.png
    - lib/assets/Laptop kecil.png
    - lib/assets/mouse.png
    - lib/assets/plus_icon.png
    - lib/assets/search-icon.png
    - lib/assets/icon_star.png
    - lib/assets/home_icon.png
    - lib/assets/keyboard.png
    - lib/assets/Iphone 16 PM.png
    - lib/assets/Laptop kecil banner.png
    - lib/assets/Iphone 16 PM banner.png
    - lib/assets/keyboard banner.png
    - lib/assets/google-icon2.png
    - lib/assets/ls-logo.png
    - lib/assets/ls-logo-removebg-preview.png
    - lib/assets/logo_kerent.png